openapi: 3.0.3
info:
  title: Arbetsgivare API
  version: 1.0.0
  description: API för att kolla om personer har arbetsgivare

paths:
  /arbetsgivare/{personnummer}:
    get:
      tags: [ArbetsgivareController]
      operationId: getArbetsgivare
      summary: Kolla om person har arbetsgivare
      description: True om personen har arbetsgivare
      parameters:
        - name: personnummer
          in: path
          required: true
          description: Svenskt personnummer 12 siffror
          schema:
            type: string
            pattern: '^\d{8}-\d{4}$'
            example: "19990101-0123"
      responses:
        '200':
          description: Förfrågan genomförd OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: True om personen har arbetsgivare
                    example: true
              examples:
                valid:
                  summary: Person har arbetsgivare
                  value:
                    result: true
                invalid:
                  summary: Person har inte arbetsgivare
                  value:
                    result: false
        '400':
          description: Bad request (t.ex. felaktigt format på personnummer)
