openapi: 3.0.3
info:
  title: Employer API
  version: 1.0.0
  description: Check if a person has an employer in Sweden

paths:
  /employer/{social_security_nr}:
    get:
      tags: [EmployerController]
      operationId: getEmployer
      summary: Check if person has employer in Sweden
      description: Returns true if person has employer in Sweden
      parameters:
        - name: social_security_nr
          in: path
          required: true
          description: Swedish social security number 12 digits
          schema:
            type: string
            pattern: '^\d{8}-\d{4}$'
            example: "19990101-0123"
      responses:
        '200':
          description: Request performed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: True if person has employer in Sweden
                    example: true
              examples:
                valid:
                  summary: Person has employer in Sweden
                  value:
                    result: true
                invalid:
                  summary: Person has no employer in Sweden
                  value:
                    result: false
        '400':
          description: Bad request (e.g. illegal format of social_security_nr)
