openapi: 3.0.3
info:
  title: Arbetsgivare API
  version: 1.0.0
  description: Kontrollera om en person har en arbetsgivare i Sverige

paths:
  /arbetsgivare/{personnummer}:
    get:
      tags: [ArbetsgivareController]
      summary: Kontrollera om personen har en arbetsgivare i Sverige
      description: Returnerar true om personen har en arbetsgivare i Sverige
      parameters:
        - name: personnummer
          in: path
          required: true
          description: Svenskt personnummer, 12 siffror
          schema:
            type: string
            pattern: '^\d{10}-\d{4}$'
      responses:
        '200':
          description: Förfrågan genomfördes utan problem
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: True om personen har en arbetsgivare i Sverige
                    example: true
              examples:
                valid:
                  summary: Personen har en arbetsgivare i Sverige
                  value:
                    result: true
                invalid:
                  summary: Personen har ingen arbetsgivare i Sverige
                  value:
                    result: false
        '400':
          description: Ogiltig förfrågan (t.ex. felaktigt format på personnummer)
